[theme]
#background = "#000000"
#primary = "#F1F1F1"
secondary = "#C6C6C6"
#title = "#1ED760"
#playing = "#FF0077"
playing_selected = "#FFD7AF"
#playing_bg = "#181818"
highlight = "#FFD7AF"
#highlight_bg = "#FFD7AF"
#error = "#FFE4E4"
#error_bg = "#A50000"
#statusbar = "#FFD7AF"
#statusbar_progress = "#FFD7AF"
#statusbar_bg = "#00AC4C"
#cmdline = "#CBFFDE"
#cmdline_bg = "#6C6C6C"
